# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BendingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tube_size", models.CharField(default="38.1 mm", max_length=100)),
                ("thickness", models.CharField(default="2.0 mm", max_length=100)),
                ("bending_spec", models.CharField(blank=True, max_length=150)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("measurements", models.JSONField(blank=True, default=list)),
                (
                    "critical_dimension_status",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold")],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("HOLD", "Hold"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bending_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bending_record",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaintRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paint_specification",
                    models.CharField(
                        default="Powder Coating / RAL 7016", max_length=150
                    ),
                ),
                (
                    "color_code",
                    models.CharField(default="Anthracite Grey", max_length=50),
                ),
                (
                    "thickness_microns",
                    models.DecimalField(decimal_places=2, default=85.0, max_digits=6),
                ),
                ("ceo_approved", models.BooleanField(default=False)),
                ("ceo_approval_date", models.DateTimeField(blank=True, null=True)),
                ("ceo_remarks", models.TextField(blank=True)),
                ("pc_approved", models.BooleanField(default=False)),
                ("pc_approval_date", models.DateTimeField(blank=True, null=True)),
                ("pc_remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("HOLD", "Hold"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_paint_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pc_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_paint_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paint_record",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PDIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_sheet_data", models.JSONField(blank=True, default=list)),
                ("is_approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("HOLD", "Hold"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdi_signoffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdi_record",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PressingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("BLANKING", "Blanking"),
                            ("FORMING", "Forming"),
                            ("PEARLING", "Pearling"),
                            ("RESTRICTING", "Restricting"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "dim_report_number",
                    models.CharField(
                        blank=True, help_text="Required for Blanking", max_length=100
                    ),
                ),
                ("quantity_produced", models.PositiveIntegerField(default=1)),
                ("measurements", models.JSONField(blank=True, default=list)),
                (
                    "critical_dimension_result",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold")],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("HOLD", "Hold"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pressing_records",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["process_type"],
                "unique_together": {("product", "process_type")},
            },
        ),
        migrations.CreateModel(
            name="WeldingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Stage 1 to 5"
                    ),
                ),
                ("stage_name", models.CharField(default="Stage 1", max_length=100)),
                ("approved_sample_id", models.CharField(blank=True, max_length=100)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("measurements", models.JSONField(blank=True, default=list)),
                (
                    "result",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold")],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("HOLD", "Hold"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_signed_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_records",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["stage_number"],
                "unique_together": {("product", "stage_number")},
            },
        ),
    ]
