# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(max_length=150)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "packing_status",
                    models.CharField(
                        default="Approved Standard Crate Packaging", max_length=150
                    ),
                ),
                (
                    "dispatch_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("vehicle_number", models.CharField(max_length=50)),
                ("transporter", models.CharField(max_length=100)),
                ("invoice_number", models.CharField(max_length=100)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready for Dispatch"),
                            ("DISPATCHED", "Dispatched"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="READY",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_record",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
