# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("part_number", models.CharField(max_length=100)),
                ("sample_name", models.CharField(max_length=200)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "drawing_file",
                    models.FileField(
                        blank=True, null=True, upload_to="samples/drawings/"
                    ),
                ),
                (
                    "sample_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="samples/images/"
                    ),
                ),
                ("critical_dimensions_summary", models.TextField(blank=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_sample_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_samples",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DRAWINGS", "Drawings"),
                            ("PFD", "PFD (Process Flow Diagram)"),
                            ("PFMEA", "PFMEA (Failure Mode & Effects Analysis)"),
                            ("CP", "CP (Control Plan)"),
                            ("PS", "PS (Process Sheet)"),
                            ("PACKING_STANDARD", "Packing Standard"),
                            ("DIM_REPORT", "DIM Report"),
                            ("CRITICAL_DIMENSION", "Critical Dimension Spec"),
                            ("INSPECTION_REPORT", "Inspection Report"),
                            ("APPROVED_SAMPLE", "Approved Sample"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAFT", "Draft"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="products.product",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("revision", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="documents/versions/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("change_summary", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
