# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CriticalDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(db_index=True, max_length=50)),
                ("parameter", models.CharField(max_length=150)),
                ("nominal_value", models.DecimalField(decimal_places=3, max_digits=10)),
                ("tolerance_min", models.DecimalField(decimal_places=3, max_digits=10)),
                ("tolerance_max", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(default="mm", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_dimensions",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("stage", models.CharField(db_index=True, max_length=50)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "result",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold")],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InspectionParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=150)),
                ("expected_value", models.CharField(max_length=100)),
                ("actual_value", models.CharField(max_length=100)),
                ("tolerance", models.CharField(blank=True, max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold")],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                ("is_critical", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="quality.inspection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("SCRAPPED", "Scrapped"),
                            ("REWORKED", "Reworked"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("corrective_action", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="products.product",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rejections",
                        to="quality.rejectionreason",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
