# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ADMIN_CREATED", "Admin Created"),
                            ("ADMIN_EDITED", "Admin Edited"),
                            ("ADMIN_SUSPENDED", "Admin Suspended"),
                            ("ADMIN_ACTIVATED", "Admin Activated"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                            ("USER_CREATED", "User Created"),
                            ("USER_EDITED", "User Edited"),
                            ("USER_SUSPENDED", "User Suspended"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PRODUCT_CREATED", "Product Created"),
                            ("PRODUCT_UPDATED", "Product Updated"),
                            ("STAGE_COMPLETED", "Stage Completed"),
                            ("INSPECTION", "Inspection"),
                            ("APPROVAL", "Approval"),
                            ("REJECTION", "Rejection"),
                            ("DISPATCH", "Dispatch"),
                            ("DOCUMENT_UPLOAD", "Document Upload"),
                            ("DOCUMENT_REVISION", "Document Revision"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="audit_audit_entity_8edb54_idx",
                    ),
                ],
            },
        ),
    ]
