# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("matrix", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50)),
                ("old_permissions", models.CharField(max_length=150)),
                ("new_permissions", models.CharField(max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_authority_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_authority_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("admins", "Admins"),
                            ("users", "Users"),
                            ("products", "Products"),
                            ("bending", "Bending"),
                            ("pressing", "Pressing"),
                            ("blanking", "Blanking"),
                            ("forming", "Forming"),
                            ("pearling", "Pearling"),
                            ("restricting", "Restricting"),
                            ("welding", "Welding"),
                            ("paint", "Paint"),
                            ("pdi", "PDI (Pre-Dispatch Inspection)"),
                            ("dispatch", "Dispatch"),
                            ("quality", "Quality Management"),
                            ("documents", "Documents"),
                            ("reports", "Reports"),
                            ("audit_logs", "Audit Logs"),
                            ("settings", "Settings"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_approve", models.BooleanField(default=False)),
                ("can_export", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Permission",
                "verbose_name_plural": "Module Permissions",
                "indexes": [
                    models.Index(
                        fields=["user", "module"], name="permissions_user_id_0ad9d7_idx"
                    )
                ],
                "unique_together": {("user", "module")},
            },
        ),
    ]
