# Generated by Django 5.2.17 on 2026-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT_ASSIGNED", "Product Assigned"),
                            ("STAGE_COMPLETED", "Stage Completed"),
                            ("APPROVAL_REQUIRED", "Approval Required"),
                            ("PRODUCT_REJECTED", "Product Rejected"),
                            ("INSPECTION_FAILED", "Inspection Failed"),
                            ("DOCUMENT_UPDATED", "Document Updated"),
                            ("READY_FOR_NEXT_STAGE", "Ready for Next Stage"),
                            ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                            ("SYSTEM", "System Alert"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                    ),
                ),
                ("link_url", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
